baseURL = "salman.github.io"
languageCode = "en-us"
title = "Salman Lee"
theme = "hurock"

[author]
  name = "Salman Lee"
  email = "vvs009@qq.com"
  
  github = "https://github.com/salmanLee"

[params]
  Description = "Welcome to Salman's site"
  # Optional
  disqusShortname = ""
  gaID = ""
  highlight_theme = "tomorrow-night"
  notoc = true


# Optional sections:
[permalinks]
  posts = "/:year/:month/:filename/"

[blackfriday]
  plainIdAnchors = true