baseURL = "https://salmanlee.github.io"
languageCode = "en-us"
title = "Salman's site"
theme = "hurock"

[author]
  name = "Salman Lee"
  email = "vvs009@163.com"
  github = "salmanLee/salmanlee.github.io"

[params]
  Description = "๑•ิ .•ั๑)"
  # Optional
  disqusShortname = ""
  gaID = ""
  highlight_theme = "tomorrow-night"
  notoc = true


# Optional sections:
[permalinks]
  notes = "/:year/:month/:filename/"

[blackfriday]
  plainIdAnchors = true

#////////////////////////////////////////////////////////////////////
#//                          _ooOoo_                               //
#//                         o8888888o                              //
#//                         88" . "88                              //
#//                         (| ^_^ |)                              //
#//                         O\  =  /O                              //
#//                      ____/`---'\____                           //
#//                    .'  \\|     |//  `.                         //
#//                   /  \\|||  :  |||//  \                        //
#//                  /  _||||| -:- |||||-  \                       //
#//                  |   | \\\  -  /// |   |                       //
#//                  | \_|  ''\---/''  |   |                       //
#//                  \  .-\__  `-`  ___/-. /                       //
#//                ___`. .'  /--.--\  `. . ___                     //
#//              ."" '<  `.___\_<|>_/___.'  >'"".                  //
#//            | | :  `- \`.;`\ _ /`;.`/ - ` : | |                 //
#//            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
#//      ========`-.____`-.___\_____/___.-`____.-'========         //
#//                           `=---='                              //
#//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
#//            佛祖保佑       永不宕机     永无BUG                    //
#///////////////////////////////////////////////////////////////////