#////////////////////////////////////////////////////////////////////
#//                          _ooOoo_                               //
#//                         o8888888o                              //
#//                         88" . "88                              //
#//                         (| ^_^ |)                              //
#//                         O\  =  /O                              //
#//                      ____/`---'\____                           //
#//                    .'  \\|     |//  `.                         //
#//                   /  \\|||  :  |||//  \                        //
#//                  /  _||||| -:- |||||-  \                       //
#//                  |   | \\\  -  /// |   |                       //
#//                  | \_|  ''\---/''  |   |                       //
#//                  \  .-\__  `-`  ___/-. /                       //
#//                ___`. .'  /--.--\  `. . ___                     //
#//              ."" '<  `.___\_<|>_/___.'  >'"".                  //
#//            | | :  `- \`.;`\ _ /`;.`/ - ` : | |                 //
#//            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
#//      ========`-.____`-.___\_____/___.-`____.-'========         //
#//                           `=---='                              //
#//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
#//            佛祖保佑       永不宕机     永无BUG                    //
#///////////////////////////////////////////////////////////////////

baseURL = "http://salmanlee.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Salman's Blog"
theme = "dream-plus"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "dream-plus"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Salman Lee"
	description = "Just a blog website of a slob."
	motto = "I hate self-introduction the most."
	enableToc = true
	enableShareCard = true

	favicon = "/img/favicon.png"

  	#Background settings
	enableColorBG= true

	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = "vvs009@163.com"
	github = "salmanLee"
	siteStartYear = 2018